 title: "Rim Jouini"
email: "rim.jouini@example.com" # ← modifie ici avec ton vrai email
description: >-
  PhD in Computer Science and member of the CRISTAL Lab – ENSI Tunisia.
baseurl: "" # ne change pas
url: "https://jouinirim.github.io"

author:
  name: "Rim Jouini"
  avatar: "/images/profile.png"  # ← ajoute une image dans /images/
  bio: "PhD in Computer Science • Data science researcher • CRISTAL Lab – ENSI"
  location: "Tunis, Tunisia"
  email: "rim.jouini@example.com"

  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=kzSy3zQAAAAJ&hl=fr"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jouinirim"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/
markdown: kramdown
highlighter: rouge
